### ISSUE TITLE
Backup fails with file creation

### ISSUE THREAD

**Issue by I-Am-Skoot** [Kaiede/Bedrockifier#64] opened 2022-12-14 17:15 UTC
I have been seeing the logs show failed backups, but I also see a new mcworld file.

docker shows the container health as unhealthy

docker-compose.yaml
<pre>
version: "4.6"
services:
  server:
    container_name: Minecraft-Skoot
    environment:
      EULA: TRUE
      SERVER_PORT: 19132
      SERVER_NAME: Skoot
      ENABLE_LAN_VISIBILITY: true
    image: "itzg/minecraft-bedrock-server:latest"
    ipc: "private"
    logging:
      driver: "json-file"
      options: {}
    networks:
      mc-network:
    ports:
     - "19132:19132"
     - "19132:19132/udp"
    stdin_open: true
    tty: true
    volumes:
      - "/opt/MCServer/minecraftbe/Skoot:/data"
    working_dir: "/data"
    labels:
      manymine.enable: true
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: always
    depends_on:
      - "server"
    tty: true
    stdin_open: true
    networks:
      mcb-network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/MCServer/backups/Skoot:/backups
      - /opt/MCServer/minecraftbe/Skoot:/server
networks:
  mc-network:
    external: true
  mcb-network:
    external: true
</pre>

Backup Logs
<pre>
DEBU[0000] Resolved UID=0 from match path               
DEBU[0000] Resolved GID=0 from match path               
[16:03:13.862][info    ] Initializing Bedrockifier Daemon
[16:03:13.865][info    ] Configuring Bedrockifier Daemon
[16:03:13.866][info    ] Loading Configuration From: /backups/config.yml
[16:03:13.870][info    ] Configuration Loaded, Running Service... (main.swift:83)
[16:03:13.909][info    ] Host PTY Handle Opened: /dev/pts/1 (6) (Terminal.swift:141)
[16:03:13.909][info    ] Child PTY Handle Opened: /dev/pts/1 (7) (Terminal.swift:162)
[16:03:13.910][debug   ] Process attached (Terminal.swift:81)
[16:03:13.910][info    ] Checking for servers that might not be cleaned up (BackupActor.swift:73)
[16:03:13.911][info    ] Backup Time: 16:05 (Service.swift:172)
[16:03:13.912][info    ] Next Backup: Dec 14, 2022, 4:05:00 PM (Service.swift:179)
[16:03:13.912][debug   ] [interval] Scheduled For Dec 14, 2022, 4:05:00 PM (ServiceTimer.swift:73)
[16:03:13.912][debug   ] [interval] Registered (ServiceTimer.swift:102)
[16:03:13.912][info    ] Service Started Successfully. (Service.swift:101)
[16:05:00.000][debug   ] [interval] Event Fired. Valid Handler: true (ServiceTimer.swift:110)
[16:05:00.001][info    ] Starting Full Backup (BackupActor.swift:159)
[16:05:00.001][debug   ] Starting Container Process (ContainerConnection.swift:69)
[16:05:00.002][debug   ] Taking save hold on Minecraft-Skoot (ContainerConnection.swift:312)
[16:05:00.179][trace   ] Sending: save hold
 (Terminal.swift:181)
[16:05:00.180][debug   ] Expecting: ["Saving", "The command is already running", "Got permission denied while trying to connect to the Docker daemon"] (Terminal.swift:227)
[16:05:00.180][trace   ] Data Received on file descriptor (6) (Terminal.swift:296)
[16:05:00.180][trace   ] Adding Expectation AA35C747-96E8-46B7-837C-F3C7E722F170 (Terminal.swift:265)
[16:05:00.180][debug   ] Timeout for Expectation is 10.0 s (Terminal.swift:271)
[16:05:00.194][trace   ] Data Received on file descriptor (6) (Terminal.swift:296)
[16:05:00.195][trace   ] Processing 1 Expects (Terminal.swift:311)
[16:05:00.195][debug   ] Content Read: save hold

 (Terminal.swift:236)
[16:05:00.195][trace   ] Content Has No Matches (Terminal.swift:241)
[16:05:01.739][trace   ] Data Received on file descriptor (6) (Terminal.swift:296)
[16:05:01.739][trace   ] Processing 1 Expects (Terminal.swift:311)
[16:05:01.739][debug   ] Content Read: Saving...

 (Terminal.swift:236)
[16:05:01.739][trace   ] Removing Expectation AA35C747-96E8-46B7-837C-F3C7E722F170 (Terminal.swift:252)
[16:05:01.739][debug   ] Match Found: Saving...

 (Terminal.swift:238)
[16:05:01.740][trace   ] Sending: save query
 (Terminal.swift:181)
[16:05:01.740][debug   ] Expecting: ["Files are now ready to be copied", "Got permission denied while trying to connect to the Docker daemon"] (Terminal.swift:227)
[16:05:01.740][trace   ] Adding Expectation 0342EFA4-1A1A-4717-B524-93149B779C89 (Terminal.swift:265)
[16:05:01.740][debug   ] Timeout for Expectation is 10.0 s (Terminal.swift:271)
[16:05:01.740][trace   ] Data Received on file descriptor (6) (Terminal.swift:296)
[16:05:01.740][trace   ] Processing 1 Expects (Terminal.swift:311)
[16:05:01.741][debug   ] Content Read: save query

 (Terminal.swift:236)
[16:05:01.741][trace   ] Content Has No Matches (Terminal.swift:241)
[16:05:01.789][trace   ] Data Received on file descriptor (6) (Terminal.swift:296)
[16:05:01.789][trace   ] Processing 1 Expects (Terminal.swift:311)
[16:05:01.789][debug   ] Content Read: A previous save has not been completed.

 (Terminal.swift:236)
[16:05:01.789][trace   ] Content Has No Matches (Terminal.swift:241)
[16:05:11.740][debug   ] Timeout Reached for 0342EFA4-1A1A-4717-B524-93149B779C89 (Terminal.swift:276)
[16:05:11.740][trace   ] Removing Expectation 0342EFA4-1A1A-4717-B524-93149B779C89 (Terminal.swift:252)
[16:05:11.740][debug   ] No Matches Found, Timed Out (Terminal.swift:245)
[16:05:11.741][trace   ] Sending: save query
 (Terminal.swift:181)
[16:05:11.741][debug   ] Expecting: ["Files are now ready to be copied", "Got permission denied while trying to connect to the Docker daemon"] (Terminal.swift:227)
[16:05:11.741][trace   ] Adding Expectation 2529E53A-5E9E-4A62-8340-497FD4EDE9ED (Terminal.swift:265)
[16:05:11.741][debug   ] Timeout for Expectation is 10.0 s (Terminal.swift:271)
[16:05:11.741][trace   ] Data Received on file descriptor (6) (Terminal.swift:296)
[16:05:11.742][trace   ] Processing 1 Expects (Terminal.swift:311)
[16:05:11.742][debug   ] Content Read: save query

 (Terminal.swift:236)
[16:05:11.742][trace   ] Content Has No Matches (Terminal.swift:241)
[16:05:11.848][trace   ] Data Received on file descriptor (6) (Terminal.swift:296)
[16:05:11.848][trace   ] Processing 1 Expects (Terminal.swift:311)
[16:05:11.848][debug   ] Content Read: Data saved. Files are now ready to be copied.

 (Terminal.swift:236)
[16:05:11.849][trace   ] Removing Expectation 2529E53A-5E9E-4A62-8340-497FD4EDE9ED (Terminal.swift:252)
[16:05:11.849][debug   ] Match Found: Data saved. Files are now ready to be copied.

 (Terminal.swift:238)
[16:05:11.849][info    ] Starting Backup of worlds for: Minecraft-Skoot (ContainerConnection.swift:124)
[16:05:11.849][info    ] Backing Up: WorldMapOSM (ContainerConnection.swift:130)
[16:18:09.142][info    ] Backed up as: WorldMapOSM.20221214-160511.mcworld (ContainerConnection.swift:132)
[16:18:09.142][info    ] Backups for Minecraft-Skoot finished successfully... (ContainerConnection.swift:158)
[16:18:09.142][trace   ] Sending: save resume
 (Terminal.swift:181)
[16:18:09.143][debug   ] Expecting: ["Changes to the level are resumed", "Changes to the world are resumed", "A previous save has not been completed", "Got permission denied while trying to connect to the Docker daemon"] (Terminal.swift:227)
[16:18:09.143][trace   ] Adding Expectation FE9E02AE-5FFE-4675-AD3C-CC4A0CE0AA58 (Terminal.swift:265)
[16:18:09.143][trace   ] Data Received on file descriptor (6) (Terminal.swift:296)
[16:18:09.143][trace   ] Processing 1 Expects (Terminal.swift:311)
[16:18:09.151][debug   ] Timeout for Expectation is 60.0 s (Terminal.swift:271)
[16:18:09.151][debug   ] Content Read: save resume

 (Terminal.swift:236)
[16:18:09.151][trace   ] Content Has No Matches (Terminal.swift:241)
[16:19:09.151][debug   ] Timeout Reached for FE9E02AE-5FFE-4675-AD3C-CC4A0CE0AA58 (Terminal.swift:276)
[16:19:09.152][trace   ] Removing Expectation FE9E02AE-5FFE-4675-AD3C-CC4A0CE0AA58 (Terminal.swift:252)
[16:19:09.152][debug   ] No Matches Found, Timed Out (Terminal.swift:245)
[16:19:09.152][error   ] Server container failed to resume autosave before timeout was reached (BackupActor.swift:182)
[16:19:09.152][error   ] Container Minecraft-Skoot failed to backup properly (BackupActor.swift:183)
[16:19:09.153][info    ] Performing Trim Jobs (BackupActor.swift:217)
[16:19:09.339][debug   ] Processing: WorldMapOSM (Backup.swift:93)
[16:19:09.340][info    ] Deleting: WorldMapOSM.20221204-014800.mcworld (Backup.swift:96)
[16:19:09.407][info    ] Full Backup Completed (BackupActor.swift:190)
[16:19:09.407][debug   ] Reseting Container Process (ContainerConnection.swift:90)
[16:19:09.408][error   ] The operation could not be completed. (PTYKit.PTYError error 4.) (BackupActor.swift:204)
[16:19:09.408][error   ] Full Backup Failed (BackupActor.swift:205)
[16:19:09.409][info    ] Next Backup: Dec 15, 2022, 4:05:00 PM (Service.swift:190)
[16:19:09.409][debug   ] [interval] Scheduled For Dec 15, 2022, 4:05:00 PM (ServiceTimer.swift:73)
</pre>

Backup Folder contents
<pre>
# ls -al
total 94196656
drwxrwxrwx 2 root root        4096 Dec 14 10:19 .
drwxr-xr-x 5 root root        4096 Dec 14 10:04 ..
-rwxrwxrwx 1 root root         215 Dec 14 10:02 config.yml
-rw-r--r-- 1 root root           0 Dec 14 10:04 .Minecraft-Skoot.hold
-rw-r--r-- 1 root root 48228664782 Dec  4 20:02 WorldMapOSM.20221205-014800.mcworld
-rw-r--r-- 1 root root 48228676543 Dec 14 10:18 WorldMapOSM.20221214-160511.mcworld
</pre>

**Comment by Kaiede** [comment] 2022-12-14 17:24
Well, the backup file is working, but the step to tell the server to resume writing to disk is timing out. So I would guess that it’s taking more than a minute to resume auto save. I wonder if you can look for the “save resume” in the Minecraft server log and see if it is resuming?

> [16:19:09.152][error   ] Server container failed to resume autosave before timeout was reached (BackupActor.swift:182)

**Comment by skenigma** [comment] 2022-12-14 17:26
Here are the server logs

<pre>
DEBU[0000] Using /data to match uid and gid             
DEBU[0000] Resolved UID=1000 from match path            
DEBU[0000] Resolved GID=0 from match path               
Looking up latest version...
Starting Bedrock server...
NO LOG FILE! - setting up server logging...
[2022-12-14 16:03:20:837 INFO] Starting Server
[2022-12-14 16:03:20:837 INFO] Version 1.19.51.01
[2022-12-14 16:03:20:837 INFO] Session ID 1f53d2ba-837d-4f03-ae00-49095b6cda78
[2022-12-14 16:03:20:838 INFO] Level Name: Skoots World
[2022-12-14 16:03:20:841 INFO] Game mode: 0 Survival
[2022-12-14 16:03:20:841 INFO] Difficulty: 1 EASY
[2022-12-14 16:03:20:905 INFO] opening worlds/Skoots World/db
[2022-12-14 16:03:20:636 INFO] IPv4 supported, port: 19132: Used for gameplay and LAN discovery
[2022-12-14 16:03:20:636 INFO] IPv6 not supported
[2022-12-14 16:03:21:920 INFO] Server started.
save hold
Saving...
save query
A previous save has not been completed.
save query
Data saved. Files are now ready to be copied.
save resume

</pre>

**Comment by Kaiede** [comment] 2022-12-14 21:44
I'm going to assume that this is correct and that there's nothing after the save resume in the server logs, even if you wait a few minutes. Which means one of three things:

1) The server is not properly resuming despite receiving the command to do so. 
2) Mojang renamed the command at some point.
3) The bedrock server now has a bug where it resumes properly, but doesn't output success/failure to the console like it should.

Let me see if I can reproduce this on my end with the latest bedrock server.

**Comment by skenigma** [comment] 2022-12-15 14:06
I can verify, there is nothing in the bedrock server logs after the save resume.

As a troubleshooting, I did attach to the server container, and try to manually run the save query command.  I got no response., nor an error with a malformed command.  so I think my server is crashing but it is not logging, or stopping.    
I am looking to find a way to increase the logging level of the server to troubleshoot some more.

**Comment by Kaiede** [comment] 2022-12-15 19:14
Another command that should always work from the server would be 'help'. 

But that does sound like a hang of some kind in the server. I haven't had a chance to try to reproduce (and might not until the weekend). I took a quick peek at the Mojang Jira and don't see any related bugs open against the Bedrock Dedicated Server.

**Comment by Kaiede** [comment] 2023-12-31 15:51
Unfortunately, due to the age of this, I need to close it out as there’s been no update since my last comment.

**Closed by Kaiede** 2023-12-31 15:51 UTC
Labels: bug
