### ISSUE TITLE
Trimming not working properly?

### ISSUE THREAD

**Issue by DanTheMan827** [Kaiede/Bedrockifier#38] opened 2022-03-01 21:27 UTC
I have this as my config.yml

```yml
containers:
  bedrock:
    - name: mcbedrock
      worlds:
        - "/server/worlds/Rad World - Redux"
        - "/server/worlds/Rad World"
schedule:
  interval: 3h
trim:
  trimDays: 2
  keepDays: 7
  minKeep: 1
loggingLevel: trace
```

Per my understanding of the documentation, I should end up with 16 hourly backups for the last day with every day thereafter trimmed to the latest backup.

However, it doesn't appear to have been trimming the hourly backups for the previous days... I set it to 7 keepDays just to test though and it did properly trim the files to that max number of days (although still every 3 hours for each day)

**Comment by Kaiede** [comment] 2022-03-01 22:04
Hmm, while I generally leave the trimming code alone, I did have to make some changes to support the new “extras” feature. It looks like the regression is due to that. Let me take a look tonight and see why it broke. 

I should have double checked my own backups folder at the end of the testing period before moving things between the test and latest tag. It would have prevented this from rolling out to users.

**Comment by Kaiede** [comment] 2022-03-02 00:33
Also need to make sure that I include a unit test covering this scenario to prevent this sort of regression from happening again. With the conversion of this code to something that uses protocols, unit testing the logic around trimming can be done with mocks, so unit tests need to be written.

**Comment by Kaiede** [comment] 2022-03-02 03:04
Fix is merged, and will appear in the test tag shortly. It can take 20 minutes due to building multi-arch docker images with QEMU. 

Things appear to be cleaned up on my local server with the fix, but I'd appreciate confirmation that the test tag works for you as well.

**Closed** 2022-03-02 15:21 UTC
Labels: bug
